"""initial

Revision ID: ba572d291d58
Revises: None
Create Date: 2026-02-24 14:40:21.848072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba572d291d58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contacts_wholesaler_id'), 'contacts', ['wholesaler_id'], unique=False)
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_index('ix_users_phone', table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_constraint('uq_wholesalers_user_id', 'wholesalers', type_='unique')
    op.drop_index('ix_wholesalers_user_id', table_name='wholesalers')
    op.create_index(op.f('ix_wholesalers_user_id'), 'wholesalers', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wholesalers_user_id'), table_name='wholesalers')
    op.create_index('ix_wholesalers_user_id', 'wholesalers', ['user_id'], unique=False)
    op.create_unique_constraint('uq_wholesalers_user_id', 'wholesalers', ['user_id'])
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.drop_index(op.f('ix_contacts_wholesaler_id'), table_name='contacts')
    # ### end Alembic commands ###
